### ISSUE TITLE
leaflet 1.0

### ISSUE THREAD

**Issue by teriblus** [Zverik/leaflet-grayscale#10]

**Comment by teriblus** [comment]
this plugin does not work with leaflet 1.0. 
I did a fix :
 if (tile.src.startsWith('http')) {

            if (/*this._layer.options.enableCanvas &&*/ !this.canvasContext) {
                var canvas = document.createElement("canvas");
                canvas.width = canvas.height = 256;//this._layer.options.tileSize;
                this.canvasContext = canvas.getContext("2d");
            }
            var ctx = this.canvasContext;

            if (ctx) {
                tile.onload = null//', null); // to prevent an infinite loop
                ctx.drawImage(tile, 0, 0);
                var imgd = ctx.getImageData(0, 0, 256/*this._layer.options.tileSize*/, 256/*this._layer.options.tileSize*/);
                var pix = imgd.data;
                for (var i = 0, n = pix.length; i < n; i += 4) {
                    pix[i] = pix[i + 1] = pix[i + 2] = (3 * pix[i] + 4 * pix[i + 1] + pix[i + 2]) / 8;
                }
                ctx.putImageData(imgd, 0, 0);
                tile.removeAttribute("crossorigin");
                tile.src = ctx.canvas.toDataURL();
            }
            done(null, tile);
            //L.TileLayer.prototype._tileOnLoad.call(done, done);
        }

**Comment by Zverik** [comment]
I've updated the plugin for Leaflet 1.0.2.
